### ISSUE TITLE
Custom font not supported (Undefined offset: 1)

### ISSUE THREAD

**Issue by MostafaNouri** [mccarlosen/laravel-mpdf#21] opened 2019-08-16 12:18 UTC
I have a problem when i want to add my custom font to my project. 

it's my _config/pdf.php_

`'custom_font_dir'      => base_path('public/font/fonts/'),
    'custom_font_data' 	   => [
        'IranSans' => [
            'R'  => 'IRANSansFaNum.ttf',
            'B'  => 'IRANSansFaNumBold.ttf',
            'I'  => 'IRANSansFaNumLight.ttf',
            'BI' => 'IRANSansFaNumMedium.ttf'
        ]
    ],`

after running project i get Undefined offset: 1 ErrorException

the problem is in vendor\mpdf\mpdf\src\Mpdf.php file and line 4105

`$ws = $fas[1] . $style;`

is this font not supported or what?

Thanks.

**Comment by mccarlosen** [comment] 2019-08-19 15:21
Verify Duplicate of #11.

**Closed by mccarlosen** 2019-08-19 15:21 UTC
